name: neuro-mne-eeg-viewer
channels:
  - conda-forge
dependencies:
  - python=3.9
  - holoviews
  - hvplot
  - panel
  - datashader
  - numpy
  - pandas
  - xarray
  - ipykernel
  - mne
  - neurodsp
  - pip
  - pip:
    - -e ../_neurodatagen