name: neuro-ephys-viewer
channels:
  - conda-forge
dependencies:
  - python=3.9
  - holoviews
  - hvplot
  - panel
  - datashader
  - numpy
  - pandas
  - xarray
  - neurodsp
  - ipykernel
  - jupyterlab
  - numcodecs
  - zarr
  - kerchunk
  - h5py
  - pip
  - pip:
    - -e ../../src/neurodatagen
    - -e ../../src/hvneuro
