name: neuro-eeg-viewer
channels:
  - conda-forge
dependencies:
  - python>3.9
  - holoviews>=1.18
  - bokeh
  - hvplot
  - panel
  - datashader
  - numpy
  - pandas
  - xarray
  - ipykernel
  - mne
  - neurodsp
  - jupyterlab
  - intake
  - zarr
  - kerchunk
  - pip
  - pip:
    - -e ../../src/neurodatagen
    - -e ../../src/hvneuro
