name: neuro-multi-chan-ts
channels:
  - conda-forge
dependencies:
  - python
  - holoviews>=1.18.1
  - bokeh>=3.3.1
  - hvplot
  - panel
  - datashader
  - numpy
  - pandas
  - xarray>=2024.5.0
  - ipykernel
  - jupyterlab
  - zarr
  - kerchunk
  - pyarrow
  - dask
  - jupyter_bokeh
  - h5py
  - pip
  - pip:
    - holonote
    - ndpyramid==0.2.0
    - tsdownsample
    - mne