name: neuro-deep-image-stack
channels:
  - conda-forge
dependencies:
  - python
  - holoviews>=1.19.0 # for wide df handling, scalebars, etc
  - hvplot
  - panel
  - datashader
  - dask
  - zarr
  - numpy
  - pandas
  - xarray>=2024.5.0
  - ipykernel
  - ffmpeg-python
  - jupyterlab
  - sparse
  - pip:
    - holonote